# Use root/example as user/password credentials
version: '3.1'

services:
  webserver:
    container_name: webserver_nginx
    image: nginx:alpine
    restart: always
    ports:
      - 8080:80
    volumes:
      - public_html:/public_html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
  php55:
    container_name: webserver_php55 # port default dari php fpm adalah 9000. tidak perlu diexpose
    image: php:5.5-fpm-alpine
    restart: always
    depends_on:
      - webserver
    volumes:
      - public_html:/public_html # php fpm juga harus mount folder public html yang sama dengan webserver seperti nginx
      # - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf lokasi konfigurasi php fpm. unkomen jika diperlukan
  php56:
    container_name: webserver_php56 # port default dari php fpm adalah 9000. tidak perlu diexpose
    image: php:5.6-fpm-alpine
    restart: always
    depends_on:
      - webserver
    volumes:
      - public_html:/public_html # php fpm juga harus mount folder public html yang sama dengan webserver seperti nginx
      # - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf lokasi konfigurasi php fpm. unkomen jika diperlukan
  php71:
    container_name: webserver_php71 # port default dari php fpm adalah 9000. tidak perlu diexpose
    image: php:7.1-fpm-alpine
    restart: always
    depends_on:
      - webserver
    volumes:
      - public_html:/public_html # php fpm juga harus mount folder public html yang sama dengan webserver seperti nginx
      # - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf lokasi konfigurasi php fpm. unkomen jika diperlukan
  php72:
    container_name: webserver_php72 # port default dari php fpm adalah 9000. tidak perlu diexpose
    image: php:7.2-fpm-alpine
    restart: always
    depends_on:
      - webserver
    volumes:
      - public_html:/public_html # php fpm juga harus mount folder public html yang sama dengan webserver seperti nginx
      # - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf lokasi konfigurasi php fpm. unkomen jika diperlukan
  db:
    container_name: webserver_mariadb
    image: mariadb:10.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - 3306:3306
  adminer:
    container_name: webserver_adminer
    image: adminer
    restart: always
    links:
      - db:database # service db yang ada diatas adminer akan dikenali dengan hostname "database" saat dibuka adminer
    ports:
      - 8081:8080
volumes:
  public_html: # folder www diberi nama public_html
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/public_html # ${pwd} = lokasi folder sekarang
      o: bind
